---
- name: chroot - install dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - chrootuid
    - makejail
  notify: stunnel - restart

- name: chroot - create dir structure
  file:
    state=directory
    dest={{ stunnel_chroot }}/{{ item }}
    mode=0700
    owner=stunnel4
    group=stunnel4
    recurse=yes
  with_items:
    - etc/stunnel
    - dev
    - tmp
    - lib
    - usr/bin
    - var/log
    - var/run
    - "{{ stunnel_ca_path }}"
    - "{{ stunnel_crl_path }}"
  notify: stunnel - restart

- name: chroot - symlink log file
  file:
    state=link
    src={{ stunnel_chroot}}/{{ stunnel_log}}
    dest={{ stunnel_log }}
    owner=root
    group=root
    force=yes

- name: chroot - copy stunnel
  command: cp -f /usr/bin/stunnel4 {{ stunnel_chroot}}/usr/bin/stunnel creates={{ stunnel_chroot}}/usr/bin/stunnel
  notify: stunnel - restart

- name: chroot - register required libs
  shell: ldd /usr/bin/stunnel4 | awk '{print $3}' | grep -Po '^/.*[0-9]$'
  register: libs

- name: chroot - copy libs
  shell: cp -a -f $(readlink -f {{ item }}) {{ stunnel_chroot}}/lib/
  with_items: libs.stdout_lines
  notify: stunnel - restart

- name: chroot - copy symlinks to libs
  command: cp -a -f {{ item }} {{ stunnel_chroot}}/lib/ creates={{ stunnel_chroot}}/lib/{{ item }}
  with_items: libs.stdout_lines
  notify: stunnel - restart

- name: chroot - copy /etc files
  command: cp -f /etc/{{ item }} {{ stunnel_chroot}}/etc/{{ item }} creates={{ stunnel_chroot}}/etc/{{ item }}
  with_items:
    - hosts
    - timezone
    - nsswitch.conf
    - resolv.conf
    - stunnel/00-stunnel.conf
    - stunnel/01-services.conf
  notify: stunnel - restart

- name: chroot - create /dev/urandom
  command: mknod -m 644 urandom c 1 9 chdir={{ stunnel_chroot }}/dev creates={{ stunnel_chroot }}/dev/urandom
  notify: stunnel - restart

- name: chroot - create /dev/null
  command: mknod -m 644 null c 1 3 chdir={{ stunnel_chroot }}/dev creates={{ stunnel_chroot }}/dev/null
  notify: stunnel - restart

- name: chroot - create /dev/zero
  command: mknod -m 644 zero c 1 5 chdir={{ stunnel_chroot }}/dev creates={{ stunnel_chroot }}/dev/zero
  notify: stunnel - restart

- name: chroot - create /etc/passwd and /etc/group
  shell: grep stunnel /etc/{{ item }} >> {{ stunnel_chroot }}/etc/{{ item }} creates={{ stunnel_chroot }}/etc/{{ item }}
  with_items:
    - passwd
    - group
  notify: stunnel - restart

- name: chroot - patch init script
  lineinfile:
    dest=/etc/init.d/stunnel4
    backrefs=yes
    regexp='^(\s+elif) (\$DAEMON \$ARGS; then)$'
    line='\1 chrootuid {{ stunnel_chroot }} stunnel4 \2'
  notify: stunnel - restart
