---
- name: install - install stunnel4 and ca-certificates
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600 state=installed
  with_items:
    - stunnel4
    - ca-certificates
  notify: stunnel - restart

- name: install - configuration
  template:
    src=stunnel.conf.j2
    dest=/etc/stunnel/stunnel.conf
    owner=root
    group=root
    mode=0644
  notify: stunnel - restart

- name: install - enable daemon
  lineinfile:
    dest=/etc/default/stunnel4
    regexp='^ENABLED=0$'
    line='ENABLED=1'
    backrefs=yes
    state=present
  notify: stunnel - restart

- name: install - enable service
  service: name=stunnel4 enabled=yes
